### ISSUE TITLE
请问有现成训练好的模型吗？请问是基于什么数据集训练的呢？

### ISSUE THREAD

**Issue by yuzhijun2** [Kxy-Moriaty/LaneSegforBaiduAI#1]

**Comment by Kxy-Moriaty** [comment]
刚搭好baseline，还在训练中。数据集：https://aistudio.baidu.com/aistudio/competition/detail/5

**Comment by yuzhijun2** [comment]
好的，谢谢您的回复！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kxy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 上午10:44
收件人:&nbsp;"Kxy-Moriaty/LaneSegforBaiduAI"<LaneSegforBaiduAI@noreply.github.com&gt;;
抄送:&nbsp;"余智君"<872528229@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kxy-Moriaty/LaneSegforBaiduAI] 请问有现成训练好的模型吗？请问是基于什么数据集训练的呢？ (#1)





 
刚搭好baseline，还在训练中。数据集：https://aistudio.baidu.com/aistudio/competition/detail/5
